export interface BlogPost {
  slug: string;
  category: string;
  title: string;
  excerpt: string;
  author: string;
  date: string;
  readTime: string;
  featured: boolean;
  color: string;
  body: string[];
}

export const posts: BlogPost[] = [
  {
    slug: "how-escrow-protects-you",
    category: "Safety",
    title: "How Escrow Payments Protect Every Buyer on Vendorspot",
    excerpt: "Your money never goes directly to a vendor until you confirm your order is exactly what you paid for. Here's exactly how escrow works on our platform.",
    author: "Olayinka Olasunkanmi",
    date: "May 10, 2026",
    readTime: "4 min read",
    featured: true,
    color: "bg-violet-500",
    body: [
      "When you pay for something online, the biggest risk is simple: you send your money, and you have no guarantee of what you'll actually receive. This is why we built escrow into the foundation of Vendorspot — not as an optional feature, but as the default for every transaction.",
      "**What is escrow?**",
      "Escrow is a neutral holding system. When you place an order on Vendorspot, your payment is held securely — it does not reach the vendor until you confirm that your order arrived exactly as described. Think of it as a trusted third party sitting between you and the seller, holding the funds until both sides are satisfied.",
      "**How it works step by step**",
      "1. You place your order and complete payment. The money is held in the Vendorspot escrow account — not in the vendor's hands.\n2. The vendor receives a notification and prepares your order for delivery.\n3. You receive your item and have a set window to inspect it.\n4. If everything matches what was advertised, you confirm receipt and the vendor is paid.\n5. If something is wrong — wrong item, damaged goods, or no delivery at all — you raise a dispute and our team steps in.",
      "**What happens if there's a problem?**",
      "You raise a dispute directly within the app. Our support team reviews the evidence from both sides — order details, photos, delivery records — and makes a fair ruling. If the fault lies with the vendor, you receive a full refund. No arguments, no long back-and-forth.",
      "**Why this matters for Nigerian e-commerce**",
      "Fraud in online transactions has been a persistent problem. Buyers have lost money to vendors who disappear after payment. With escrow, that risk is eliminated. Vendors on Vendorspot know they will be paid — but only when they deliver. This creates a system where honesty is not just expected, it is enforced.",
      "Shopping on Vendorspot should feel safe. Escrow is the reason it is.",
    ],
  },
  {
    slug: "grow-your-shop",
    category: "Vendor Stories",
    title: "From Side Hustle to 500+ Orders: How Enis Perfumery Grew on Vendorspot",
    excerpt: "Seyifunmi started selling fragrances from her bedroom. Two years later, she's one of our top verified vendors. This is her story.",
    author: "Vendorspot Team",
    date: "May 3, 2026",
    readTime: "6 min read",
    featured: false,
    color: "bg-rose-400",
    body: [
      "Seyifunmi Alonge started Enis Perfumery the way most Nigerian side businesses start — out of necessity, with very little capital, and a lot of faith. In 2022, she was blending and selling fragrances to friends and family via WhatsApp. It was going well enough, but growth was slow and she had no way to reach new customers beyond word of mouth.",
      "\"I tried selling on other platforms,\" she says, \"but the buyers weren't serious and the platforms didn't protect me. I had people request delivery and then claim they never received their items.\"",
      "**Joining Vendorspot**",
      "Seyifunmi joined the Vendorspot vendor community in mid-2022, when the platform was still in its community phase — curating and verifying a network of trusted sellers before the marketplace launched. The verification process was thorough. She submitted her business details, went through a review, and received her verified badge.",
      "\"The verification changed how buyers treated me. When they saw the badge, they trusted me immediately. I didn't have to convince anyone.\"",
      "**The escrow difference**",
      "What surprised her most was how escrow changed her relationship with buyers. \"Before, I was always anxious after I shipped. Would they claim they didn't receive it? Would they demand a refund for no reason? With Vendorspot's escrow, everything is structured. The buyer pays, I ship, they confirm, I get paid. It's clean.\"",
      "**The numbers**",
      "By early 2023, Enis Perfumery had processed over 200 orders through the platform. By the end of the year, that number had crossed 500. Seyifunmi now employs two people to help with packaging and logistics.",
      "Her advice to other vendors: \"Stop selling informally. Get verified, use escrow, and treat it like a real business. The buyers who want quality are on Vendorspot — you just need to show up properly.\"",
    ],
  },
  {
    slug: "tips-for-safe-buying",
    category: "Tips & Guides",
    title: "5 Things to Always Check Before You Buy from Any Online Store",
    excerpt: "Online shopping fraud is real. These five checks take less than two minutes and could save you from losing money to fake vendors.",
    author: "Vendorspot Team",
    date: "Apr 28, 2026",
    readTime: "3 min read",
    featured: false,
    color: "bg-amber-400",
    body: [
      "Online shopping in Nigeria has grown enormously — and so has the fraud that comes with it. Before you hand over your money to any online seller, run through these five checks. They take less than two minutes and have saved thousands of shoppers from loss.",
      "**1. Check for a verification badge**",
      "On Vendorspot, every trusted vendor carries a verified badge. This means we have reviewed their business, confirmed their identity, and held them to our standards. If a vendor has no badge, treat them with extra caution and look closely at their order history.",
      "**2. Read recent reviews — not just the star rating**",
      "A 4.8-star rating means little if the last three reviews are complaints about late delivery or wrong items. Read the actual text of recent reviews. Look for patterns, not averages.",
      "**3. Check the product photos carefully**",
      "Are the photos generic stock images, or do they show the actual product? Ask the vendor for additional photos if you are unsure. Legitimate sellers are happy to provide them. Fraudulent ones are not.",
      "**4. Confirm the return and refund policy before you pay**",
      "Any serious vendor should be clear about what happens if your order is wrong or damaged. On Vendorspot, our escrow system and 100% refund guarantee cover you regardless — but it is still good practice to read the vendor's own policy.",
      "**5. Never pay outside the platform**",
      "If a vendor asks you to pay via bank transfer directly, via WhatsApp, or via any method outside the platform's official checkout, walk away. This is the most common fraud method. Payment through the platform protects you. Payment outside it does not.",
      "Shopping smart is the foundation of shopping safely. Use platforms that protect you by design, not by luck.",
    ],
  },
  {
    slug: "vendor-verification-explained",
    category: "Updates",
    title: "What Our Vendor Verification Process Actually Looks Like",
    excerpt: "We don't just tick a box. Every verified badge on Vendorspot represents a real business that has passed our multi-step review process.",
    author: "Olayinka Olasunkanmi",
    date: "Apr 18, 2026",
    readTime: "5 min read",
    featured: false,
    color: "bg-teal-500",
    body: [
      "One of the most common questions we receive from buyers is: what does your verified badge actually mean? The honest answer is that it means more than most people realise.",
      "**The problem with unverified marketplaces**",
      "Most marketplaces allow anyone to create a seller account and start listing products within minutes. This speed is convenient, but it is also dangerous. Bad actors exploit it constantly — creating fake stores, listing products they do not have, collecting payments, and disappearing.",
      "We built our verification process specifically to close this gap.",
      "**Step 1: Business identity review**",
      "Every vendor who applies to sell on Vendorspot must submit verifiable identity documents and, where applicable, business registration information. We cross-check these against public records.",
      "**Step 2: Product and listing review**",
      "We review the vendor's initial product listings for accuracy. Are the photos real? Is the pricing reasonable? Does the description match what is actually being sold? Listings that are vague, misleading, or copied from other sources are flagged.",
      "**Step 3: Standards agreement**",
      "Every vendor must agree to our seller standards — covering delivery timelines, returns, communication, and behaviour in disputes. This is not a formality. Vendors who repeatedly violate these standards lose their badge and, ultimately, their ability to sell on the platform.",
      "**Step 4: Ongoing monitoring**",
      "Verification is not a one-time event. We monitor vendor performance continuously — tracking order completion rates, dispute outcomes, and buyer reviews. A vendor who earns their badge today must maintain standards to keep it.",
      "When you see the verified badge, you are not just seeing a tick. You are seeing evidence of a real business that has been reviewed, agreed to our standards, and continues to be held accountable.",
    ],
  },
  {
    slug: "sell-better-photos",
    category: "Tips & Guides",
    title: "Better Product Photos = More Sales. Here's How to Take Them With Your Phone",
    excerpt: "You don't need a DSLR or a studio. With the right setup and these simple tips, your product photos will stand out in any marketplace.",
    author: "Vendorspot Team",
    date: "Apr 10, 2026",
    readTime: "5 min read",
    featured: false,
    color: "bg-blue-500",
    body: [
      "The single biggest difference between a vendor who sells consistently and one who struggles is often not price, not product quality — it is photos. Buyers cannot touch or try your products. Your images are the only thing standing between them and clicking \"add to cart.\"",
      "The good news: you do not need expensive equipment. Here is how to take great product photos with the phone already in your pocket.",
      "**Use natural light — always**",
      "The best light source for product photography is a window during the day. Place your product close to the window (but not in direct harsh sunlight, which creates unflattering shadows). Natural light is even, flattering, and free.",
      "**Use a clean, simple background**",
      "A white or neutral-coloured surface works best. A plain piece of A3 paper or card, or a light-coloured fabric, is enough. The background should not compete with your product.",
      "**Shoot from multiple angles**",
      "Take at least 4–5 photos of every product: front, back, side, top, and a detail shot of any important feature. Buyers want to see exactly what they are getting.",
      "**Clean your lens first**",
      "This sounds obvious but is often forgotten. A smudged lens makes every photo slightly blurry. Wipe it before every shoot.",
      "**Do not over-edit**",
      "Filters and heavy editing can make products look different from reality — which leads to disputes and returns. Adjust brightness and contrast slightly if needed, but keep your photos honest.",
      "Great photos build trust. Trust drives sales. Your phone is powerful enough — use it well.",
    ],
  },
  {
    slug: "refund-policy-guide",
    category: "Safety",
    title: "Understanding the 100% Refund Guarantee — and When It Applies",
    excerpt: "Our refund guarantee isn't just marketing. Here's a plain-English breakdown of what it covers, how to claim it, and what to do if a vendor disputes.",
    author: "Vendorspot Team",
    date: "Apr 2, 2026",
    readTime: "4 min read",
    featured: false,
    color: "bg-emerald-500",
    body: [
      "We say \"100% refund guaranteed\" on Vendorspot, and we mean it. But like any policy, there are specifics worth understanding — so you know exactly what you are entitled to and how to claim it if things go wrong.",
      "**What the guarantee covers**",
      "Our refund guarantee covers three core situations:\n\n1. You do not receive your order at all.\n2. You receive an item that is significantly different from what was advertised.\n3. Your item arrives damaged or defective.",
      "**What is not covered**",
      "The guarantee does not cover buyer's remorse — changing your mind after receiving an item that matches the listing exactly. It also does not cover situations where the buyer provides an incorrect delivery address or refuses delivery without cause.",
      "**How to raise a dispute**",
      "If you believe your order qualifies for a refund, open a dispute within the app within the allowed window after your delivery date. Provide photos, a description of the issue, and any relevant communication with the vendor.",
      "**What happens next**",
      "Our support team reviews the dispute, contacts the vendor for their response, and makes a ruling within 3–5 business days. If the ruling is in your favour, the funds held in escrow are released back to you — not to the vendor.",
      "**If a vendor disputes the claim**",
      "Vendors can submit evidence — delivery confirmation, photos of the item before shipping, communication records. We weigh all evidence fairly. Our goal is not to favour buyers or vendors automatically — it is to find what actually happened and rule accordingly.",
      "The refund guarantee exists because we believe safe commerce requires accountability on both sides. When you shop on Vendorspot, you have a real safety net — not just a marketing promise.",
    ],
  },
];

export function getPost(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug);
}
